### ISSUE TITLE
Consider organization field

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-service-info#21]
Consider whether to add an `organization` property.

Beacon provides a structured version of this:

```yaml
        organization:
          $ref: '#/components/schemas/BeaconOrganization'
```

```yaml
    BeaconOrganization:
      description: Organization owning the beacon.
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: Unique identifier of the organization.
        name:
          type: string
          description: Name of the organization.
        description:
          type: string
          description: Description of the organization.
        address:
          type: string
          description: Address of the organization.
        welcomeUrl:
          type: string
          description: URL of the website of the organization (RFC 3986 format).
        contactUrl:
          type: string
          description: >-
            URL with the contact for the beacon operator/maintainer, e.g. link
            to a contact form (RFC 3986 format) or an email (RFC 2368 format).
        logoUrl:
          type: string
          description: >-
            URL to the logo (PNG/JPG/SVG format) of the organization (RFC 3986
            format).
        info:
          description: 'Additional unspecified metadata about the host Organization.'
          type: object
          example:
            additionalInfoKey: additionalInfoValue
```

In the case of Beacon, this was UI-driven (Beacon Network). In our case, we probably only need a single unstrcutured field, e.g. `organization` or `organizationId`. Thoughts?
