### ISSUE TITLE
Elaborate on error responses

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-service-info#25]
Consider adding common errors in the spec - status codes and error object structure to allow the clients to better handle errors.

**Comment by andrewyatz** [comment]
Possible content
```yaml
        '404':
          description: 'Service info could not be found'
        '500':
          description: 'The service is not available. Should be used to communicate to downstream users and aggregators that the service is not yet ready to accept requests'
```
