### ISSUE TITLE
schemaUrl to document the API schema used by the service

### ISSUE THREAD

**Issue by susheel** [ga4gh-discovery/ga4gh-service-info#26]
I feel it may be worth adding the explicit URL to the API schema used by the service. This would allow clients to detect the API schema used by the service and self-configure. This could point to the GA4GH YAML spec or a local copy that may add non-breaking extensions. See example below:
```yaml
schemaUrl:
  type: string
  description: URL of the schema of this service (RFC 3986 format).
````

Related [GA4GH DRS /service-info PR #277](https://github.com/ga4gh/data-repository-service-schemas/pull/277#discussion_r291835815) discussion.
