### ISSUE TITLE
Add field for service maturity

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-service-info#33]
Add a field indicating whether a particular service is prod vs. test etc. This should be an optional string field.

**Comment by mcupak** [comment]
Requested by Jordi (ELIXIR Beacon).

**Comment by andrewyatz** [comment]
Suggested change

```yaml
        maturity:
          type: string
          description: 'Describes the level of maturity of the service deployed. Used to flag if a service is production ready or is serving another purpose'
          enum: [prod, dev, test, unknown]
          default: unknown
```
