### ISSUE TITLE
Explain how to extend the specification by other specifications

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-service-info#35]
E.g. Beacon wants to have an image URL for organizations.

**Comment by mcupak** [comment]
The consensus seems to be to encourage a single top-level extension object for everything, incl. `organizationImageUrl`.

**Comment by andrewyatz** [comment]
Just tried this in refget as I've never done inheritance using OpenAPI before. Works really well!

```YAML
    RefgetServiceInfo:
      allOf:
      - '$ref': https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/develop/service-info.yaml#/components/schemas/ServiceInfo
      - type: object
        description: Extended capabilities of refget service info
        properties:
          extension:
            type: object
            required:
              - circular_supported
              - algorithms
            properties:
              circular_supported:
                type: boolean
                description: Indicates if the service supports circular location queries
              subsequence_limit:
                type: integer
                format: int64
                nullable: true
                description: Maximum length of sequence which may be requested using start and/or end query parameters
              algorithms:
                type: array
                items:
                  type: string
                  description: An array of strings listing the digest algorithms that are supported
                  example:
                  - md5
                  - trunc512
```

However the example response looks like

```json
{
  "id": "org.ga4gh.service",
  "name": "1000 Genomes Project",
  "type": "org.ga4gh:beacon:1.0.1",
  "description": "The 1000 Genomes Project provides a large public catalogue of\nhuman genome variation data which serves as standard reference\nin many genomic workflows and analysis projects.\n",
  "documentationUrl": "https://docs.example.com",
  "organization": "EMBL-EBI",
  "contactUrl": "mailto:support@example.com",
  "version": "1.0.0",
  "extension": {
    "circular_supported": true,
    "subsequence_limit": 0,
    "algorithms": [
      [
        "md5",
        "trunc512"
      ]
    ]
  },
  "createdAt": "2019-06-04T12:58:19Z",
  "updatedAt": "2019-06-04T12:58:19Z"
}
```

We should make the OpenAPI more generic in the examples so it doesn't look this odd when we integrate it into 3rd party applications
